name: Build slides

on:
  push:
    paths:
      - "slides/**/*.md"
      - "package.json"
      - ".github/workflows/build-pptx.yml"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm install
      - run: mkdir -p dist
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: slides-pptx-and-pdf
          path: dist/*